### ISSUE TITLE
Request schema validation

### ISSUE THREAD

**Issue by dveljacic** [mkon/openapi_contracts#41]
Hi @mkon, 

I would really love to see the feature of **_Request schema validation_** working similarly to _Response schema validation_ and I see you put it in [Future Plans](https://github.com/mkon/openapi_contracts#future-plans). Do you have any idea when this could be? 

I would like to try implementing this myself but first wanted to check with you and see what you think about it, maybe you have some general guidelines or ideas you want me to follow or something like that.

Thank you in advance for your response. 
Best regards.

**Comment by mkon** [comment]
Hey @dveljacic,

I am currently working on a feature that allows generating some kind of coverage report and request body validation would be quite high on the list of the next things to work on, but I can not really say when that is going to happen. Most likely not within the next 1-2 months.

If you want to work on it, you are welcome to submit a PR and I will review it.

Some general ideas how to implement it:
- add another [validator class](https://github.com/mkon/openapi_contracts/tree/main/lib/openapi_contracts/validators) for the request body and include it in the list of validators
- add a Request class similar to the [Response class](https://github.com/mkon/openapi_contracts/blob/main/lib/openapi_contracts/doc/response.rb) and a way to lookup the correct request from the doc similar to the response
- Also it would make sense for me to bring the refactoring from #40 upstream so we do not have too many conflicts

**Comment by dveljacic** [comment]
Closed by: https://github.com/mkon/openapi_contracts/pull/56
