### ISSUE TITLE
Support for ruby 3.3

### ISSUE THREAD

**Issue by JProgrammer** [mkon/openapi_contracts#82]
Ruby 3.3 has been released in December.

Could openapi_contracts be upgraded/modified to support the new stable version.

**Comment by mkon** [comment]
Hi @JProgrammer, I will add ruby 3.3 to the tested ruby versions and if there is no issue I can publish a new version straight away.

**Comment by mkon** [comment]
There is now version `0.12.0` supporting ruby 3.3
https://github.com/mkon/openapi_contracts/pull/83
https://github.com/mkon/openapi_contracts/releases/tag/v0.12.0
